//auth
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE"
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST"
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const SIGN_UP_FAILURE_DELETE = "SIGN_UP_FAILURE_DELETE"

export const LOG_IN_FAILURE = "LOG_IN_FAILURE"
export const LOG_IN_REQUEST = "LOG_IN_REQUEST"
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS"
export const LOG_IN_FAILURE_DELETE = "LOG_IN_FAILURE_DELETE"

export const SOCIAL_LOGIN_FAILURE = "SOCIAL_LOGIN_FAILURE"
export const SOCIAL_LOGIN_REQUEST = "SOCIAL_LOGIN_REQUEST"
export const SOCIAL_LOGIN_SUCCESS = "SOCIAL_LOGIN_SUCCESS"

export const LOG_OUT_FAILURE = "LOG_OUT_FAILURE"
export const LOG_OUT_REQUEST = "LOG_OUT_REQUEST"
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS"

export const LOAD_MY_INFO_SUCCESS = "LOAD_MY_INFO_SUCCESS"
export const LOAD_MY_INFO_REQUEST = "LOAD_MY_INFO_REQUEST"
export const LOAD_MY_INFO_FAILURE = "LOAD_MY_INFO_FAILURE"

export const LOAD_USER_FAILURE = "LOAD_USER_FAILURE"
export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"

export const USER_PROFILE_FAILURE = "USER_PROFILE_FAILURE"
export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST"
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS"

export const USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE"
export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST"
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS"

export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE"
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST"
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"

export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE"
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"

export const CONFIRM_FAILURE = "CONFIRM_FAILURE"
export const CONFIRM_REQUEST = "CONFIRM_REQUEST"
export const CONFIRM_SUCCESS = "CONFIRM_SUCCESS"

export const GET_CONU_TRAN_FAILURE = "GET_CONU_TRAN_FAILURE"
export const GET_CONU_TRAN_REQUEST = "GET_CONU_TRAN_REQUEST"
export const GET_CONU_TRAN_SUCCESS = "GET_CONU_TRAN_SUCCESS"


//faq
export const FAQ_ADD_RESET = "FAQ_ADD_RESET";

export const FAQ_GET_REQUEST = "FAQ_GET_REQUEST";
export const FAQ_GET_SUCCESS = "FAQ_GET_SUCCESS";
export const FAQ_GET_FAILURE = "FAQ_GET_FAILURE";

export const FAQ_NOT_GET_REQUEST = "FAQ_NOT_GET_REQUEST";
export const FAQ_NOT_GET_SUCCESS = "FAQ_NOT_GET_SUCCESS";
export const FAQ_NOT_GET_FAILURE = "FAQ_NOT_GET_FAILURE";

export const FAQ_RELATED_REQUEST = "FAQ_RELATED_REQUEST";
export const FAQ_RELATED_SUCCESS = "FAQ_RELATED_SUCCESS";
export const FAQ_RELATED_FAILURE = "FAQ_RELATED_FAILURE";

export const FAQ_UPLOAD_IMAGES_REQUEST = "FAQ_UPLOAD_IMAGES_REQUEST";
export const FAQ_UPLOAD_IMAGES_SUCCESS = "FAQ_UPLOAD_IMAGES_SUCCESS";
export const FAQ_UPLOAD_IMAGES_FAILURE = "FAQ_UPLOAD_IMAGES_FAILURE";

export const FAQ_REMOVE_UPDATE_IMAGE_REQUEST = "FAQ_REMOVE_UPDATE_IMAGE_REQUEST";
export const FAQ_REMOVE_UPDATE_IMAGE_SUCCESS = "FAQ_REMOVE_UPDATE_IMAGE_SUCCESS";
export const FAQ_REMOVE_UPDATE_IMAGE_FAILURE = "FAQ_REMOVE_UPDATE_IMAGE_FAILURE";

export const FAQ_UPDATE_RESET = "FAQ_UPDATE_RESET";


export const FAQ_REMOVE_IMAGE = "FAQ_REMOVE_IMAGE"

export const FAQ_READ_REQUEST = "FAQ_READ_REQUEST";
export const FAQ_READ_SUCCESS = "FAQ_READ_SUCCESS";
export const FAQ_READ_FAILURE = "FAQ_READ_FAILURE";

export const FAQ_ADD_REQUEST = "FAQ_ADD_REQUEST";
export const FAQ_ADD_SUCCESS = "FAQ_ADD_SUCCESS";
export const FAQ_ADD_FAILURE = "FAQ_ADD_FAILURE";

export const FAQ_DELETE_REQUEST = "FAQ_DELETE_REQUEST";
export const FAQ_DELETE_SUCCESS = "FAQ_DELETE_SUCCESS";
export const FAQ_DELETE_FAILURE = "FAQ_DELETE_FAILURE";

export const FAQ_UPDATE_REQUEST = "FAQ_UPDATE_REQUEST";
export const FAQ_UPDATE_SUCCESS = "FAQ_UPDATE_SUCCESS";
export const FAQ_UPDATE_FAILURE = "FAQ_UPDATE_FAILURE";


export const FAQ_MOUSE_MOVE_REQUEST = "FAQ_MOUSE_MOVE_REQUEST";
export const FAQ_MOUSE_MOVE_SUCCESS = "FAQ_MOUSE_MOVE_SUCCESS";
export const FAQ_MOUSE_MOVE_FAILURE = "FAQ_MOUSE_MOVE_FAILURE";

export const FAQ_SEARCH_REQUEST = "FAQ_SEARCH_REQUEST";
export const FAQ_SEARCH_SUCCESS = "FAQ_SEARCH_SUCCESS";
export const FAQ_SEARCH_FAILURE = "FAQ_SEARCH_FAILURE";


//post
export const POST_ADD_RESET = "POST_ADD_RESET";

export const POST_GET_REQUEST = "POST_GET_REQUEST";
export const POST_GET_SUCCESS = "POST_GET_SUCCESS";
export const POST_GET_FAILURE = "POST_GET_FAILURE";

export const POST_NOT_GET_REQUEST = "POST_NOT_GET_REQUEST";
export const POST_NOT_GET_SUCCESS = "POST_NOT_GET_SUCCESS";
export const POST_NOT_GET_FAILURE = "POST_NOT_GET_FAILURE";

export const POST_RELATED_REQUEST = "POST_RELATED_REQUEST";
export const POST_RELATED_SUCCESS = "POST_RELATED_SUCCESS";
export const POST_RELATED_FAILURE = "POST_RELATED_FAILURE";

export const POST_UPLOAD_IMAGES_REQUEST = "POST_UPLOAD_IMAGES_REQUEST";
export const POST_UPLOAD_IMAGES_SUCCESS = "POST_UPLOAD_IMAGES_SUCCESS";
export const POST_UPLOAD_IMAGES_FAILURE = "POST_UPLOAD_IMAGES_FAILURE";

export const POST_REMOVE_UPDATE_IMAGE_REQUEST = "POST_REMOVE_UPDATE_IMAGE_REQUEST";
export const POST_REMOVE_UPDATE_IMAGE_SUCCESS = "POST_REMOVE_UPDATE_IMAGE_SUCCESS";
export const POST_REMOVE_UPDATE_IMAGE_FAILURE = "POST_REMOVE_UPDATE_IMAGE_FAILURE";

export const POST_UPDATE_RESET = "POST_UPDATE_RESET";
export const POST_REMOVE_IMAGE = "POST_REMOVE_IMAGE"

export const POST_READ_REQUEST = "POST_READ_REQUEST";
export const POST_READ_SUCCESS = "POST_READ_SUCCESS";
export const POST_READ_FAILURE = "POST_READ_FAILURE";

export const POST_ADD_REQUEST = "POST_ADD_REQUEST";
export const POST_ADD_SUCCESS = "POST_ADD_SUCCESS";
export const POST_ADD_FAILURE = "POST_ADD_FAILURE";

export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_FAILURE = "POST_DELETE_FAILURE";

export const POST_UPDATE_REQUEST = "POST_UPDATE_REQUEST";
export const POST_UPDATE_SUCCESS = "POST_UPDATE_SUCCESS";
export const POST_UPDATE_FAILURE = "POST_UPDATE_FAILURE";


export const POST_MOUSE_MOVE_REQUEST = "POST_MOUSE_MOVE_REQUEST";
export const POST_MOUSE_MOVE_SUCCESS = "POST_MOUSE_MOVE_SUCCESS";
export const POST_MOUSE_MOVE_FAILURE = "POST_MOUSE_MOVE_FAILURE";

export const POST_SEARCH_REQUEST = "POST_SEARCH_REQUEST";
export const POST_SEARCH_SUCCESS = "POST_SEARCH_SUCCESS";
export const POST_SEARCH_FAILURE = "POST_SEARCH_FAILURE";

//Q&A
export const QNA_ADD_RESET = "QNA_ADD_RESET";

export const QNA_GET_REQUEST = "QNA_GET_REQUEST";
export const QNA_GET_SUCCESS = "QNA_GET_SUCCESS";
export const QNA_GET_FAILURE = "QNA_GET_FAILURE";

export const QNA_NOT_GET_REQUEST = "QNA_NOT_GET_REQUEST";
export const QNA_NOT_GET_SUCCESS = "QNA_NOT_GET_SUCCESS";
export const QNA_NOT_GET_FAILURE = "QNA_NOT_GET_FAILURE";

export const QNA_RELATED_REQUEST = "QNA_RELATED_REQUEST";
export const QNA_RELATED_SUCCESS = "QNA_RELATED_SUCCESS";
export const QNA_RELATED_FAILURE = "QNA_RELATED_FAILURE";

export const QNA_UPLOAD_IMAGES_REQUEST = "QNA_UPLOAD_IMAGES_REQUEST";
export const QNA_UPLOAD_IMAGES_SUCCESS = "QNA_UPLOAD_IMAGES_SUCCESS";
export const QNA_UPLOAD_IMAGES_FAILURE = "QNA_UPLOAD_IMAGES_FAILURE";



export const QNA_REMOVE_UPDATE_IMAGE_REQUEST = "QNA_REMOVE_UPDATE_IMAGE_REQUEST";
export const QNA_REMOVE_UPDATE_IMAGE_SUCCESS = "QNA_REMOVE_UPDATE_IMAGE_SUCCESS";
export const QNA_REMOVE_UPDATE_IMAGE_FAILURE = "QNA_REMOVE_UPDATE_IMAGE_FAILURE";

export const QNA_UPDATE_RESET = "QNA_UPDATE_RESET";


export const QNA_REMOVE_IMAGE = "QNA_REMOVE_IMAGE"

export const QNA_READ_REQUEST = "QNA_READ_REQUEST";
export const QNA_READ_SUCCESS = "QNA_READ_SUCCESS";
export const QNA_READ_FAILURE = "QNA_READ_FAILURE";

export const QNA_ADD_REQUEST = "QNA_ADD_REQUEST";
export const QNA_ADD_SUCCESS = "QNA_ADD_SUCCESS";
export const QNA_ADD_FAILURE = "QNA_ADD_FAILURE";

export const QNA_DELETE_REQUEST = "QNA_DELETE_REQUEST";
export const QNA_DELETE_SUCCESS = "QNA_DELETE_SUCCESS";
export const QNA_DELETE_FAILURE = "QNA_DELETE_FAILURE";

export const QNA_UPDATE_REQUEST = "QNA_UPDATE_REQUEST";
export const QNA_UPDATE_SUCCESS = "QNA_UPDATE_SUCCESS";
export const QNA_UPDATE_FAILURE = "QNA_UPDATE_FAILURE";




export const QNA_SEARCH_REQUEST = "QNA_SEARCH_REQUEST";
export const QNA_SEARCH_SUCCESS = "QNA_SEARCH_SUCCESS";
export const QNA_SEARCH_FAILURE = "QNA_SEARCH_FAILURE";


//Answer
export const ANSWER_ADD_RESET = "ANSWER_ADD_RESET";

export const ANSWER_GET_REQUEST = "ANSWER_GET_REQUEST";
export const ANSWER_GET_SUCCESS = "ANSWER_GET_SUCCESS";
export const ANSWER_GET_FAILURE = "ANSWER_GET_FAILURE";

export const ANSWER_NOT_GET_REQUEST = "ANSWER_NOT_GET_REQUEST";
export const ANSWER_NOT_GET_SUCCESS = "ANSWER_NOT_GET_SUCCESS";
export const ANSWER_NOT_GET_FAILURE = "ANSWER_NOT_GET_FAILURE";

export const ANSWER_RELATED_REQUEST = "ANSWER_RELATED_REQUEST";
export const ANSWER_RELATED_SUCCESS = "ANSWER_RELATED_SUCCESS";
export const ANSWER_RELATED_FAILURE = "ANSWER_RELATED_FAILURE";

export const ANSWER_UPLOAD_IMAGES_REQUEST = "ANSWER_UPLOAD_IMAGES_REQUEST";
export const ANSWER_UPLOAD_IMAGES_SUCCESS = "ANSWER_UPLOAD_IMAGES_SUCCESS";
export const ANSWER_UPLOAD_IMAGES_FAILURE = "ANSWER_UPLOAD_IMAGES_FAILURE";



export const ANSWER_REMOVE_UPDATE_IMAGE_REQUEST = "ANSWER_REMOVE_UPDATE_IMAGE_REQUEST";
export const ANSWER_REMOVE_UPDATE_IMAGE_SUCCESS = "ANSWER_REMOVE_UPDATE_IMAGE_SUCCESS";
export const ANSWER_REMOVE_UPDATE_IMAGE_FAILURE = "ANSWER_REMOVE_UPDATE_IMAGE_FAILURE";

export const ANSWER_UPDATE_RESET = "ANSWER_UPDATE_RESET";
export const ANSWER_REMOVE_IMAGE = "ANSWER_REMOVE_IMAGE"


export const ANSWER_READ_REQUEST = "ANSWER_READ_REQUEST";
export const ANSWER_READ_SUCCESS = "ANSWER_READ_SUCCESS";
export const ANSWER_READ_FAILURE = "ANSWER_READ_FAILURE";

export const ANSWER_ADD_REQUEST = "ANSWER_ADD_REQUEST";
export const ANSWER_ADD_SUCCESS = "ANSWER_ADD_SUCCESS";
export const ANSWER_ADD_FAILURE = "ANSWER_ADD_FAILURE";

export const ANSWER_DELETE_REQUEST = "ANSWER_DELETE_REQUEST";
export const ANSWER_DELETE_SUCCESS = "ANSWER_DELETE_SUCCESS";
export const ANSWER_DELETE_FAILURE = "ANSWER_DELETE_FAILURE";

export const ANSWER_UPDATE_REQUEST = "ANSWER_UPDATE_REQUEST";
export const ANSWER_UPDATE_SUCCESS = "ANSWER_UPDATE_SUCCESS";
export const ANSWER_UPDATE_FAILURE = "ANSWER_UPDATE_FAILURE";




export const ANSWER_SEARCH_REQUEST = "ANSWER_SEARCH_REQUEST";
export const ANSWER_SEARCH_SUCCESS = "ANSWER_SEARCH_SUCCESS";
export const ANSWER_SEARCH_FAILURE = "ANSWER_SEARCH_FAILURE";


//Invoice
export const INVOICE_ADD_RESET = "INVOICE_ADD_RESET";

export const INVOICE_RESET = "INVOICE_RESET";

export const INVOICE_GET_REQUEST = "INVOICE_GET_REQUEST";
export const INVOICE_GET_SUCCESS = "INVOICE_GET_SUCCESS";
export const INVOICE_GET_FAILURE = "INVOICE_GET_FAILURE";

export const INVOICE_LIKE_GET_REQUEST = "INVOICE_LIKE_GET_REQUEST";
export const INVOICE_LIKE_GET_SUCCESS = "INVOICE_LIKE_GET_SUCCESS";
export const INVOICE_LIKE_GET_FAILURE = "INVOICE_LIKE_GET_FAILURE";

export const INVOICE_ADMIN_GET_REQUEST = "INVOICE_ADMIN_GET_REQUEST";
export const INVOICE_ADMIN_GET_SUCCESS = "INVOICE_ADMIN_GET_SUCCESS";
export const INVOICE_ADMIN_GET_FAILURE = "INVOICE_ADMIN_GET_FAILURE";

export const INVOICE_CHART_ADMIN_GET_REQUEST = "INVOICE_CHART_ADMIN_GET_REQUEST";
export const INVOICE_CHART_ADMIN_GET_SUCCESS = "INVOICE_CHART_ADMIN_GET_SUCCESS";
export const INVOICE_CHART_ADMIN_GET_FAILURE = "INVOICE_CHART_ADMIN_GET_FAILURE";

export const INVOICE_RELATED_REQUEST = "INVOICE_RELATED_REQUEST";
export const INVOICE_RELATED_SUCCESS = "INVOICE_RELATED_SUCCESS";
export const INVOICE_RELATED_FAILURE = "INVOICE_RELATED_FAILURE";

export const INVOICE_READ_REQUEST = "INVOICE_READ_REQUEST";
export const INVOICE_READ_SUCCESS = "INVOICE_READ_SUCCESS";
export const INVOICE_READ_FAILURE = "INVOICE_READ_FAILURE";

export const INVOICE_ADD_REQUEST = "INVOICE_ADD_REQUEST";
export const INVOICE_ADD_SUCCESS = "INVOICE_ADD_SUCCESS";
export const INVOICE_ADD_FAILURE = "INVOICE_ADD_FAILURE";

export const INVOICE_DELETE_REQUEST = "INVOICE_DELETE_REQUEST";
export const INVOICE_DELETE_SUCCESS = "INVOICE_DELETE_SUCCESS";
export const INVOICE_DELETE_FAILURE = "INVOICE_DELETE_FAILURE";

export const INVOICE_UPDATE_REQUEST = "INVOICE_UPDATE_REQUEST";
export const INVOICE_UPDATE_SUCCESS = "INVOICE_UPDATE_SUCCESS";
export const INVOICE_UPDATE_FAILURE = "INVOICE_UPDATE_FAILURE";



export const INVOICE_SEARCH_REQUEST = "INVOICE_SEARCH_REQUEST";
export const INVOICE_SEARCH_SUCCESS = "INVOICE_SEARCH_SUCCESS";
export const INVOICE_SEARCH_FAILURE = "INVOICE_SEARCH_FAILURE";



//LIKE
export const JJIM_LIKE_SUCCESS = "JJIM_LIKE_SUCCESS"
export const JJIM_LIKE_REQUEST = "JJIM_LIKE_REQUEST"
export const JJIM_LIKE_FAILURE = "JJIM_LIKE_FAILURE"
export const JJIM_UNLIKE_SUCCESS = "JJIM_UNLIKE_SUCCESS"
export const JJIM_UNLIKE_REQUEST = "JJIM_UNLIKE_REQUEST"
export const JJIM_UNLIKE_FAILURE = "JJIM_UNLIKE_FAILURE"
export const JJIM_LIKE_PUSH = "JJIM_LIKE_PUSH"
export const JJIM_UNLIKE_PUSH = "JJIM_UNLIKE_PUSH"